name: CI

on:
  push:
    tags:
     - v*

jobs:
  build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: sh ./scripts/release.sh
